=== halestudio/hale-core/io/plugins/eu.esdihumboldt.hale.io.gml/resources/test/data/group/choice2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="items" type="ItemsType"/>

  <xs:complexType name="ItemsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="shirt" type="xs:string"/>
      <xs:element name="hat" type="xs:string"/>
      <xs:element name="umbrella" type="xs:string"/>
      <xs:choice minOccurs="1" maxOccurs="1">
      	<xs:element name="tent" type="xs:string"/>
      	<xs:element name="house" type="xs:string"/>
      </xs:choice>
    </xs:choice>
  </xs:complexType>

</xs:schema>

=== halestudio/hale-core/io/plugins/eu.esdihumboldt.hale.io.gml/resources/test/data/group/choice2.xml
<?xml version="1.0" ?>

<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="choice2.xsd">
	<shirt>Some shirt</shirt>
	<hat>Some hat</hat>
	<shirt>Some other shirt</shirt>
	<house>Some house</house>
	<umbrella>Some umbrella</umbrella>
	<hat>And another shirt</hat>
	<tent>Some tent</tent>
</items>
